language: node_js
node_js:
  - 0.10

before_script:
    - chmod 777 ./test/travis/setup_arangodb.sh
    - ./test/travis/setup_arangodb.sh
    - npm install -g karma
    - npm install -g karma-mocha
    - npm install -g karma-chai
    - sh -e /etc/init.d/xvfb start

script: make test

