language: node_js
node_js:
  - 0.10

matrix:
    - MODE='check'
    - BROWSER=Android-Chrome ARGS=''
    - BROWSER=Chrome-stable ARGS='-x -b Chrome -u'
    - BROWSER=Chrome-beta ARGS='-x -b Chrome -u'
    - BROWSER=Chrome-unstable ARGS='-x -b Chrome -u'
    - BROWSER=Firefox-stable ARGS='-x -b Firefox -u'
    - BROWSER=Firefox-beta ARGS='-x -b Firefox -u'
    - BROWSER=Firefox-aurora ARGS='-x -b Firefox -u'
    - BROWSER=Remote ARGS='--verbose -b Remote --sauce --remote-caps=INTERNETEXPLORER --remote-caps=version=10 --remote-caps=platform="Windows 8"'
    - BROWSER=Remote ARGS='--verbose -b Remote --sauce --remote-caps=SAFARI --remote-caps=version=6 --remote-caps=platform="OS X 10.8"'
    - BROWSER=Remote ARGS='--verbose -b Remote --sauce --remote-caps=IPHONE --remote-caps=version=6 --remote-caps=platform="OS X 10.8"'
    - BROWSER=Remote ARGS='--verbose -b Remote --sauce --remote-caps=ANDROID --remote-caps=version=4.0 --remote-caps=platform=Linux'

matrix:
# Disabled until travis-ci/travis-ci#1696 is fixed.
#  fast_finish: true
  allow_failures:
    - env: BROWSER=Remote ARGS='--verbose -b Remote --sauce --remote-caps=INTERNETEXPLORER --remote-caps=version=10 --remote-caps=platform="Windows 8"'
    - env: BROWSER=Remote ARGS='--verbose -b Remote --sauce --remote-caps=SAFARI --remote-caps=version=6 --remote-caps=platform="OS X 10.8"'
    - env: BROWSER=Remote ARGS='--verbose -b Remote --sauce --remote-caps=IPHONE --remote-caps=version=6 --remote-caps=platform="OS X 10.8"'
    - env: BRO

before_script:
    - chmod 777 ./test/travis/setup_arangodb.sh
    - chmod 777 ./test/travis/browser_setup.sh
    - ./test/travis/setup_arangodb.sh
    - ./test/travis/browser_setup.sh
    - npm install -g karma
    - npm install -g karma-mocha
    - npm install -g karma-chai

script: make test

