language: node_js
node_js:
  - 0.10.22

addons:
  firefox: "17.0"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
before_script:
  - chmod 777 ./test/travis/setup_arangodb.sh
  - ./test/travis/setup_arangodb.sh

script: make test

